### ISSUE TITLE
The SetupCommand throws a Fatal Error due to getDescription() not being a valid method

### ISSUE THREAD

**Issue by garretthyder** [10quality/wpmvc-commands#1]
Hello,

Using the WPMVC I ran into an issue where the setup would fatal error out failing to create my project. The cause is the `getDescription()` isn't a method and should be `__get('description')` instead.

Error;
Fatal error: Uncaught Error: Call to undefined method WPMVC\Commands\SetupCommand::getDescription() in /Users/garretthyder/Work/WordPress/plugin-scaffold/wp-content/plugins/sendtonews/vendor/10quality/wpmvc-commands/src/SetupCommand.php:72
Stack trace:
#0 /Users/garretthyder/Work/WordPress/plugin-scaffold/wp-content/plugins/sendtonews/vendor/10quality/ayuco/src/Listener.php(149): WPMVC\Commands\SetupCommand->call(Array)
#1 /Users/garretthyder/Work/WordPress/plugin-scaffold/wp-content/plugins/sendtonews/vendor/10quality/ayuco/src/Listener.php(129): Ayuco\Listener->call('setup')
#2 /Users/garretthyder/Work/WordPress/plugin-scaffold/wp-content/plugins/sendtonews/ayuco(23): Ayuco\Listener->interpret()
#3 {main}
  thrown in /Users/garretthyder/Work/WordPress/plugin-scaffold/wp-content/plugins/sendtonews/vendor/10quality/wpmvc-commands/src/SetupCommand.php on line 72

**Comment by amostajo** [comment]
Commit cc2df0fe1db029f8183aeb350123a0cae5b871ec fixes this.

**Comment by garretthyder** [comment]
Thanks @amostajo
