### ISSUE TITLE
Avoid Code Duplication

### ISSUE THREAD

**Issue by garretthyder** [10quality/wpmvc-commands#20]
Hello @amostajo 

I tried to figure this out myself but am unsure if PHP-Parser has a way to determine if the node to be injected already exists.

What I'm hoping to avoid is running the same command twice can generate multiple identical entries in the Main.php.
Also if you are generating the controller along with a method and run it twice accidentally you introduce the same method in the controller class a second time which will produce an error.

Are you aware of how to check if the node to be added already exists? 

It would be nice to catch it and avoid adding a second method of the same name to the class.

Thank you

**Comment by amostajo** [comment]
@garretthyder let me review PHP-Parser.

If it doesn't have a checker, then maybe we can stop the command by finding a regex match within the file contents.

**Comment by garretthyder** [comment]
Thanks @amostajo that would be awesome.

I don't know PHP-Parser very well so couldn't say if this does the trick but was leaning in it's direction as it sounded similar to what's desired;
https://github.com/nikic/PHP-Parser/blob/master/doc/component/Name_resolution.markdown

If not I guess the other option (aside from REGEX) is parsing the file, and traversing through until the desired parent node then check all child nodes to ensure there's not a match. I don't know the level of work involved with that though.

**Comment by amostajo** [comment]
@garretthyder I tried and tested with the `NameResolver` first, but it was not working as expected. It was much easier to add regex calls to the `BaseCommand` to provide global checking and it works perfectly.

**Comment by garretthyder** [comment]
Awesome @amostajo glad to hear, thanks for the update.
