### ISSUE TITLE
Deprecate SetName Command in favour of Set Command

### ISSUE THREAD

**Issue by garretthyder** [10quality/wpmvc-commands#28]
Hello @amostajo 

After getting through all the commands and testing things out I feel it would make sense to deprecate the SetName command and instead use the Set command and add namespace as an available object option.

I've started this in a branch here;
https://github.com/garretthyder/wpmvc-commands/tree/deprecate-setname

I still have to finalize the Unit Tests and get it functioning but wanted to see if it's worth pursuing.

I'll also need your assistance getting it implemented as the ayuco project contains a stub for the command which probably should be deprecated as well it can be found here;
https://github.com/10quality/ayuco/blob/v1.0/src/Commands/SetNameCommand.php

Am just thinking the Set command will be used moving forward to add additional object setters so we might as well move all SetName code into that and use a SetNameSpaceTrait similar to the other trait setters.

Thoughts?

**Comment by amostajo** [comment]
@garretthyder makes sense. Go for it.

**Comment by garretthyder** [comment]
I've created #59 to work on this deprecation but would appreciate guidance.
