### ISSUE TITLE
During File/Method/Trait creation apply existing version

### ISSUE THREAD

**Issue by garretthyder** [10quality/wpmvc-commands#33]
When the stubs get created for Assets/Models/Traits/etc they are created with comments like - `@version fill`. It would be nice if this pre-populated with the current version from config. So when users are working on a new version they can update the version using the SetCommand and then when they create new stubs the `@version` is populated.

**Comment by amostajo** [comment]
Agreed! I was planning to create an issue in this regards.

**Comment by amostajo** [comment]
#34  Includes this.
