### ISSUE TITLE
Add author as an option for the SetCommand

### ISSUE THREAD

**Issue by garretthyder** [10quality/wpmvc-commands#34]
It would be nice to define `author` in the app.php config and use it to populate the `style.css` or `plugin.php` which would have to be done during setup like the textdomain. Also this can then be used when the stubs are generated to populate the `@author` definitions.

**Comment by garretthyder** [comment]
Thanks for adding my suggestion @amostajo testing I found a few issues which I've addressed in #40 

Also am curious about the following;
1. Should we add author info to the package.json or composer.json?
2. The Author and Author URI in plugin.php/style.css should they be updated?
3. Should the @author info on Main.php be updated from 'fill'. And should any existing files with `@author fill` get updated when the author is set, mainly thinking for pre-existing projects.

**Comment by garretthyder** [comment]
O and once this is released I guess the docs here will need an update;
https://www.wordpress-mvc.com/v1/ayuco/

**Comment by amostajo** [comment]
> Thanks for adding my suggestion @amostajo testing I found a few issues which I've addressed in #40
> 
> Also am curious about the following;
> 
> 1. Should we add author info to the package.json or composer.json?
> 2. The Author and Author URI in plugin.php/style.css should they be updated?
> 3. Should the @author info on Main.php be updated from 'fill'. And should any existing files with `@author fill` get updated when the author is set, mainly thinking for pre-existing projects.

Yes, the Main class needs to be filled on setup, and or maybe everytime something is added to it. Will create a new issue for this.
