### ISSUE TITLE
Create asset on registration or provide warning

### ISSUE THREAD

**Issue by garretthyder** [10quality/wpmvc-commands#45]
Hello @amostajo 

Running the register asset command it's very easy to introduce an invalid asset to your project resulting in a 404 reference. It would be nice to create the asset or indicate it doesn't exist so the user realizes they need to do a manual step.

For example;
`php ayuco register asset:css/admin.css`

If we decide it should generate the file if it doesn't exist we can probably use `createAsset` with some modifications to avoid creating the file within the raw folder and to intelligently determine the type (js|css|scss|sass) from the supplied filename to load the appropriate template.

Otherwise if we don't want to generate the asset then we can just do a file_exists check using the supplied filename and output a comment along the lines of;
`The css/admin.css asset doesn't exist!!!`

**Comment by amostajo** [comment]
@garretthyder btw, take a look at:
https://www.wordpress-mvc.com/v1/assets/#enqueue

**Comment by garretthyder** [comment]
Thanks for the update on this warning I'm sure it'll save me from introducing invalid assets.

And I appreciate the link, I feel I overlooked that and definitely needed to know how the packaging process worked. Thank you
