### ISSUE TITLE
Multi line on lengthy con-cat strings

### ISSUE THREAD

**Issue by amostajo** [10quality/wpmvc-commands#78]
Pretty printer, this:

```php
$name = 'very large string ' . $variable_large . ' another large string ' . $very_large_valiable_name . 'ver long end';
```

To:

```php
$name = 'very large string '
    . $variable_large
    . ' another large string '
    . $very_large_valiable_name
    . 'ver long end';
```

**Comment by garretthyder** [comment]
Is it not more appropriate to print that as follows;
```
$name = 'very large string ' .
        $variable_large .
        ' another large string ' .
        $very_large_valiable_name .
        'ver long end';
```
So all string parts are aligned, even the first one.

**Comment by amostajo** [comment]
@garretthyder yes, let's make it as you suggest, as it follows PSR-2 standards:
https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartV/CodingGuideLines/PHP.html

**Comment by garretthyder** [comment]
Awesome thanks @amostajo reading PSR-2 again my example had indented the following lines with spaces until it aligned with the first string. But from PSR-2 it indicates just to do a single tab indent for following lines so I guess it won't always line up with the first part of the string but that makes sense especially when we have long variable names.
